name: Package Publishing
on:
  release:
    types:
      - published

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  PyPi-Package-Release:
    if: github.repository == 'Anselmoo/pandas2tensorboard'
    name: Publish on PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.TWINE_TOKEN }}
          poetry publish --build
        continue-on-error: true
